version: "3"

services:
  app:
    build: .
    command: npm run start
    ports:
      - "3007:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - "mongo"
    networks:
      - backend

networks:
  backend:
    driver: bridge