version: "3"

services:
  app:
    build: .
    command: npm run start
    ports:
      - "3005:3000"
    volumes:
      - .:/usr/app
    networks:
      - backend

networks:
  backend:
    driver: bridge